<?php

namespace AppBundle\Repository;

/**
 * MarisupilamiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MarisupilamiRepository extends \Doctrine\ORM\EntityRepository
{
}
